[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  targetPort = 5173
  framework = "vite"

[context.production.environment]
  NPM_FLAGS = "--legacy-peer-deps"