[build]
  # 1. Base directory set karna sabse zaroori hai
  base = "."
  
  # 2. --legacy-peer-deps force karega install ko
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

  
  # 3. Publish path relative to base
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    # Google Login Fix
    Cross-Origin-Opener-Policy = "unsafe-none"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Permissions-Policy = "interest-cohort=()"
    X-Frame-Options = "ALLOW-FROM https://accounts.google.com"