[build]
  # 1. Base directory set karna sabse zaroori hai
  base = "frontend"
  
  # 2. --legacy-peer-deps force karega install ko
  command = "npm install --legacy-peer-deps && npm run build"
  
  # 3. Publish path relative to base
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    # Google Login Fix
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"